mutation AddAnswer($answer:String, $name: String, $email: String, $anonymous: Boolean, $questionId: ID, $allowed: Boolean, $status: String, $productId: String) {
  addAnswer(answer: $answer, name: $name, email:$email, anonymous: $anonymous, questionId: $questionId, allowed: $allowed, status: $status, productId: $productId)
}