mutation AddQuestion($productId: String!, $question: String, $name: String, $email: String, $anonymous: Boolean, $allowed: Boolean) {
  addQuestion(productId: $productId, question: $question, name: $name, email: $email, anonymous: $anonymous, allowed: $allowed)
}
