query GetAllAnswers($filter: AnswersFilter){
  answersV2(filter: $filter){
  	id
    answer
    name
    email
    anonymous
    votes
    allowed
    questionId
    question {
      questionText
      product {
        Name
        LinkId
      }
    }
  }
}
