query GetQuestions($productId: String!) {
  questions(productId: $productId) {
    id
    question
    name
    email
    anonymous
    votes
    allowed
    status
    answers {
      id
      answer
      votes
      name
      email
      anonymous
      allowed
      status
    }
  }
}
