query SearchQuestions($keyword: String!) {
  search(keyword: $keyword) {
    id
    question
    name
    email
    anonymous
    votes
    allowed
    answers {
      id
      answer
      votes
      name
      email
      anonymous
      allowed
    }
  }
}
