query SearchQuestions($keyword: String, $productId: String) {
  search(keyword: $keyword, productId: $productId) {
    id
    question
    name
    email
    anonymous
    votes
    allowed
    answers {
      id
      answer
      votes
      name
      email
      anonymous
      allowed
    }
  }
}
